In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 31 11:47:08 2017

@author: albertobiella
"""

from qutip import *
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import *

PI=np.pi
idmat = qeye(2)

#parameter definition
Lx=2
Ly=1
V=2.0
hx=0.3
Gamma=1.0

#Hilbert space dimension
d=2

print('g=',hx)
#construct the Hamiltonian and dissipators
H=0
diss=[]
ii=-1
for i in range(Lx):
    for j in range(Ly):
        ii=ii+1
        op = [idmat for i in range(Lx*Ly)]
        op[ii]=hx*0.5*sigmax()
        H=H+tensor(op)
        
        if ii<(Lx-1):
            op = [idmat for i in range(Lx*Ly)]
            op[ii] = V*0.25*sigmaz()
            op[ii+1] = sigmaz()
            H=H+tensor(op)
        
        op = [idmat for i in range(Lx*Ly)]
        op[ii]=np.sqrt(Gamma)*sigmam()
        diss.append(tensor(op))
 
#enforcing periodic BC
op = [idmat for i in range(Lx*Ly)]
op[0]=V*0.25*sigmaz()
op[Lx-1]=sigmaz()
H=H+tensor(op)
        
#observables
obs=[]
Stotx=0
Stoty=0
Stotz=0
ii=-1
for i in range(Lx):
    for j in range(Ly):
        ii=ii+1
        op = [idmat for i in range(Lx*Ly)]
        op[ii]=sigmax()
        Stotx=Stotx+tensor(op)
        op[ii]=sigmay()
        Stoty=Stoty+tensor(op)
        op[ii]=sigmaz()
        Stotz=Stotz+tensor(op)
obs.append(Stotx)
obs.append(Stoty)
obs.append(Stotz)
        
#initial state
op = [fock_dm(2,0) for i in range(Lx*Ly)]
psi0up=tensor(op)
op = [fock_dm(2,1) for i in range(Lx*Ly)]
psi0do=tensor(op)
times = np.linspace(0, 50.0, 1001)

#evolving the ME
opts = Options(store_final_state=True)
data=mesolve(H, psi0up, times, diss, obs, options=opts)
#rhoSS=data.final_state

#fill the opuput
output[n,0]=hx
output[n,1]=data.expect[0][-1]
output[n,2]=data.expect[1][-1]
output[n,3]=data.expect[2][-1]

g= 0.3


NameError: name 'output' is not defined

In [23]:
output

array([[ 0.3       ,  0.27598264,  0.08141487, -1.97557554]])

In [24]:
H

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.    0.15  0.15  0.  ]
 [ 0.15 -1.    0.    0.15]
 [ 0.15  0.   -1.    0.15]
 [ 0.    0.15  0.15  1.  ]]

In [30]:
data.final_state

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 4.65718895e-04+6.66139424e-20j  6.43359039e-09-1.55240286e-03j
   6.43359039e-09-1.55240286e-03j -5.17467504e-03-2.06986959e-02j]
 [ 6.43359039e-09+1.55240286e-03j  5.64039562e-03+7.78569250e-19j
   5.17467504e-03+2.92477276e-18j  6.89956532e-02-1.88013141e-02j]
 [ 6.43359039e-09+1.55240286e-03j  5.17467504e-03+2.49143404e-18j
   5.64039562e-03+4.92423308e-18j  6.89956532e-02-1.88013141e-02j]
 [-5.17467504e-03+2.06986959e-02j  6.89956532e-02+1.88013141e-02j
   6.89956532e-02+1.88013141e-02j  9.88253490e-01-6.13449787e-18j]]

In [ ]:
[[ 4.65720660e-04  4.58116894e-17 -2.33591393e-16 -5.17467400e-03]
 [ 6.55830501e-17  5.64039466e-03  5.17467400e-03  6.89956533e-02]
 [ 1.06186674e-16  5.17467400e-03  5.64039466e-03  6.89956533e-02]
 [-5.17467400e-03  6.89956533e-02  6.89956533e-02  9.88253490e-01]]


[[ 4.48231214e-17  1.55240220e-03  1.55240220e-03  2.06986960e-02]
 [-1.55240220e-03  7.29129204e-17  8.98873569e-17  1.88013155e-02]
 [-1.55240220e-03 -4.51365698e-17 -1.96749150e-17  1.88013155e-02]
 [-2.06986960e-02 -1.88013155e-02 -1.88013155e-02 -9.87603578e-17]]


In [32]:
tensor([sigmax(), idmat])

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

In [34]:
tensor([idmat, sigmay()])

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]]

In [44]:
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))



In [47]:
(liouvillian(H, diss).data.todense().imag)

matrix([[0, -0.15, -0.15, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0],
        [-0.15, 2, 0, -0.15, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0],
        [-0.15, 0, 2, -0.15, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0],
        [0, -0.15, -0.15, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0],
        [0.15, 0, 0, 0, -2, -0.15, -0.15, 0, 0, 0, 0, 0, 0.15, 0, 0, 0],
        [0, 0.15, 0, 0, -0.15, 0, 0, -0.15, 0, 0, 0, 0, 0, 0.15, 0, 0],
        [0, 0, 0.15, 0, -0.15, 0, 0, -0.15, 0, 0, 0, 0, 0, 0, 0.15, 0],
        [0, 0, 0, 0.15, 0, -0.15, -0.15, -2, 0, 0, 0, 0, 0, 0, 0, 0.15],
        [0.15, 0, 0, 0, 0, 0, 0, 0, -2, -0.15, -0.15, 0, 0.15, 0, 0, 0],
        [0, 0.15, 0, 0, 0, 0, 0, 0, -0.15, 0, 0, -0.15, 0, 0.15, 0, 0],
        [0, 0, 0.15, 0, 0, 0, 0, 0, -0.15, 0, 0, -0.15, 0, 0, 0.15, 0],
        [0, 0, 0, 0.15, 0, 0, 0, 0, 0, -0.15, -0.15, -2, 0, 0, 0, 0.15],
        [0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, -0.15, -0.15, 0],
        [0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, -0.15, 2,

In [52]:
np.array([[0, -0.15, -0.15, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0],
       [-0.15, 2, 0, -0.15, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0],
       [-0.15, 0, 2, -0.15, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0],
       [0, -0.15, -0.15, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0],
       [0.15, 0, 0, 0, -2, -0.15, -0.15, 0, 0, 0, 0, 0, 0.15, 0, 0, 0],
       [0, 0.15, 0, 0, -0.15, 0, 0, -0.15, 0, 0, 0, 0, 0, 0.15, 0, 0],
       [0, 0, 0.15, 0, -0.15, 0, 0, -0.15, 0, 0, 0, 0, 0, 0, 0.15, 0],
       [0, 0, 0, 0.15, 0, -0.15, -0.15, -2, 0, 0, 0, 0, 0, 0, 0, 0.15],
       [0.15, 0, 0, 0, 0, 0, 0, 0, -2, -0.15, -0.15, 0, 0.15, 0, 0, 0],
       [0, 0.15, 0, 0, 0, 0, 0, 0, -0.15, 0, 0, -0.15, 0, 0.15, 0, 0],
       [0, 0, 0.15, 0, 0, 0, 0, 0, -0.15, 0, 0, -0.15, 0, 0, 0.15, 0],
       [0, 0, 0, 0.15, 0, 0, 0, 0, 0, -0.15, -0.15, -2, 0, 0, 0, 0.15],
       [0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, -0.15, -0.15, 0],
       [0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, -0.15, 2, 0, -0.15],
       [0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, -0.15, 0, 2, -0.15],
       [0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, -0.15, -0.15, 0]])

array([[0, -0.15, -0.15, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0],
       [-0.15, 2, 0, -0.15, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0],
       [-0.15, 0, 2, -0.15, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0],
       [0, -0.15, -0.15, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0],
       [0.15, 0, 0, 0, -2, -0.15, -0.15, 0, 0, 0, 0, 0, 0.15, 0, 0, 0],
       [0, 0.15, 0, 0, -0.15, 0, 0, -0.15, 0, 0, 0, 0, 0, 0.15, 0, 0],
       [0, 0, 0.15, 0, -0.15, 0, 0, -0.15, 0, 0, 0, 0, 0, 0, 0.15, 0],
       [0, 0, 0, 0.15, 0, -0.15, -0.15, -2, 0, 0, 0, 0, 0, 0, 0, 0.15],
       [0.15, 0, 0, 0, 0, 0, 0, 0, -2, -0.15, -0.15, 0, 0.15, 0, 0, 0],
       [0, 0.15, 0, 0, 0, 0, 0, 0, -0.15, 0, 0, -0.15, 0, 0.15, 0, 0],
       [0, 0, 0.15, 0, 0, 0, 0, 0, -0.15, 0, 0, -0.15, 0, 0, 0.15, 0],
       [0, 0, 0, 0.15, 0, 0, 0, 0, 0, -0.15, -0.15, -2, 0, 0, 0, 0.15],
       [0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, -0.15, -0.15, 0],
       [0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.15, 0, 0, -0.15, 2, 0, -0.15],
  

In [53]:
lio=liouvillian(H, diss)

In [62]:
lio.groundstate()[1].data.todense()

matrix([[ 0.50257367+0.j        ],
        [ 0.06695592+0.01681386j],
        [ 0.06695592+0.01681386j],
        [-0.02296686+0.00995865j],
        [ 0.06695592-0.01681386j],
        [-0.48990178+0.j        ],
        [ 0.02296686+0.j        ],
        [ 0.03442676-0.0582056j ],
        [ 0.06695592-0.01681386j],
        [ 0.02296686+0.j        ],
        [-0.48990178+0.j        ],
        [ 0.03442676-0.0582056j ],
        [-0.02296686-0.00995865j],
        [ 0.03442676+0.0582056j ],
        [ 0.03442676+0.0582056j ],
        [ 0.47722989+0.j        ]])

In [73]:
steadystate(lio).data.todense().reshape((-1,1))

matrix([[ 4.65720660e-04+0.00000000e+00j],
        [-2.90566182e-17-1.55240220e-03j],
        [ 2.65629532e-18-1.55240220e-03j],
        [-5.17467400e-03-2.06986960e-02j],
        [-2.90566182e-17+1.55240220e-03j],
        [ 5.64039466e-03+0.00000000e+00j],
        [ 5.17467400e-03-3.13613949e-18j],
        [ 6.89956533e-02-1.88013155e-02j],
        [ 2.65629532e-18+1.55240220e-03j],
        [ 5.17467400e-03+3.13613949e-18j],
        [ 5.64039466e-03+0.00000000e+00j],
        [ 6.89956533e-02-1.88013155e-02j],
        [-5.17467400e-03+2.06986960e-02j],
        [ 6.89956533e-02+1.88013155e-02j],
        [ 6.89956533e-02+1.88013155e-02j],
        [ 9.88253490e-01+0.00000000e+00j]])

In [ ]:
[[ 4.65720660e-04-1.17605414e-16j]
 [-7.02888208e-17+1.55240220e-03j]
 [ 1.48013739e-16+1.55240220e-03j]
 [-5.17467400e-03+2.06986960e-02j]
 [-1.39515342e-16-1.55240220e-03j]
 [ 5.64039466e-03+1.71384329e-16j]
 [ 5.17467400e-03+1.87672922e-17j]
 [ 6.89956533e-02+1.88013155e-02j]
 [-1.93515570e-16-1.55240220e-03j]
 [ 5.17467400e-03-7.15281703e-17j]
 [ 5.64039466e-03+1.79174526e-16j]
 [ 6.89956533e-02+1.88013155e-02j]
 [-5.17467400e-03-2.06986960e-02j]
 [ 6.89956533e-02-1.88013155e-02j]
 [ 6.89956533e-02-1.88013155e-02j]
 [ 9.88253490e-01-3.62598250e-16j]]
[ ]:
