In [1]:
import netket as nk
import numpy as np

In [2]:
N = 1
hi = nk.hilbert.Spin(0.5, N)

In [3]:
ii = 0

sx = nk.operator.spin.sigmax(hi, ii)
sy = nk.operator.spin.sigmay(hi, ii)
sz = nk.operator.spin.sigmaz(hi, ii)

sm = nk.operator.spin.sigmam(hi, ii)
sp = nk.operator.spin.sigmap(hi, ii)

In [27]:
_sx = np.array([[0, 1], [1, 0]])
_sy = np.array([[0, -1.0j], [1.0j, 0]])
_sz = np.array([[1, 0], [0, -1]])
_sm = np.array([[0, 0], [1, 0]])
_sp = np.array([[0, 1], [0, 0]])

In [31]:
-1j*_sx@_sy@_sz

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [15]:
0.5*(sx -1j*sy).to_dense()

array([[0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j]])

In [5]:
sm.to_dense()

array([[0., 1.],
       [0., 0.]])

In [16]:
(-1j*sx@sy@sz).to_dense()

array([[-1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [19]:
sy.to_dense()

array([[0.+0.j, 0.+1.j],
       [0.-1.j, 0.+0.j]])

In [6]:
# Metropolis Local Sampling
hi = nk.hilbert.Spin(0.5, N)
op = nk.operator.spin.sigmax(hi, 0) + nk.operator.spin.sigmay(hi, 0) 
vs = nk.variational.MCMixedState(nk.sampler.MetropolisLocal(nk.hilbert.DoubledHilbert(hi)), nk.models.NDM(beta=1,), n_samples=300, n_samples_diag=200)

vs.init_parameters()

In [7]:
vs.to_matrix()

DeviceArray([[0.50104564+0.j        , 0.4997226 +0.00772518j],
             [0.4997226 -0.00772518j, 0.49895436+0.j        ]],            dtype=complex128)

In [8]:
op.operators

[array([[0.+0.j, 1.+1.j],
        [1.-1.j, 0.+0.j]])]

In [9]:
op.to_dense()

array([[0.+0.j, 1.+1.j],
       [1.-1.j, 0.+0.j]])

In [10]:
vs.expect(op)

0.984+0.105j ± 0.070 [σ²=1.019, R̂=1.3440]

In [11]:
np.trace(op@vs.to_matrix())

(1.0148955668546005+0j)

In [12]:
op.is_hermitian

True

In [13]:
_sx@_sy

NameError: name '_sx' is not defined

In [ ]:
_sx@_sy.conj()